In [3]:
#63 generate a 2d matrix usings strides with a window length of 4 and strides of 2 like [[0,1,2,3],[2,3,4,5],[4,5,6,7]]
import numpy as np
a1 = np.arange(15)
print(a1)

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [4]:
print(gen_strides(np.arange(25), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14 15]
 [14 15 16 17]
 [16 17 18 19]
 [18 19 20 21]
 [20 21 22 23]]


In [5]:
print(gen_strides(np.arange(15), stride_len=3, window_len=4))

[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]]


In [6]:
print(gen_strides(np.arange(35), stride_len=3, window_len=4))

[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]
 [15 16 17 18]
 [18 19 20 21]
 [21 22 23 24]
 [24 25 26 27]
 [27 28 29 30]
 [30 31 32 33]]
