In [1]:
#13 swap columns and rows of 2d array
import numpy as np
a1 = np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
# swap first and second column
a2 = a1[:, [1,0,2]]
print(a2)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [4]:
# swap first and last column
a3 = a1[:,[2,1,0]]
print(a3)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [5]:
# swap first and second row
a4 = a1[[1,0,2],:]
print(a4)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [6]:
# swap first and last row
a5 = a1[[2,1,0],:]
print(a5)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [7]:
# swap first and last row and column at the same time
a6 = a1[[2,1,0],[2,1,0]]
print(a6)

[8 4 0]


In [8]:
#14 create a 2d array containing random floats between 5 and 10
rand_a7 = np.random.randint(low=5,high=10,size=(5,3)) + np.random.random((5,3))
print(rand_a7)

[[8.18240794 5.56843216 7.86776567]
 [6.58755413 9.97583123 7.98963855]
 [9.95685285 9.70227757 9.32247811]
 [8.50801168 7.77805958 8.82448886]
 [9.94929498 9.2032825  5.58262787]]


In [9]:
#15 only print 3 decimal places in numpy array
np.set_printoptions(precision=3)
rand_a7[:4]

array([[8.182, 5.568, 7.868],
       [6.588, 9.976, 7.99 ],
       [9.957, 9.702, 9.322],
       [8.508, 7.778, 8.824]])

In [11]:
#16 suppressing the secientific notation like le10
np.random.seed(100)
rand_a8 = np.random.random([3,3])/1e3
rand_a8

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [14]:
np.set_printoptions(suppress=True, precision=6)
rand_a8

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [15]:
#17 limit the number of items printed in output of numpy array
a9 = np.arange(16)
a9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
np.set_printoptions(threshold=6)
a9

array([ 0,  1,  2, ..., 13, 14, 15])

In [21]:
#18 print out full without truncating
import sys # should import sys first 
np.set_printoptions(threshold=sys.maxsize)
a9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
#19 import a dataset with numbers and texts keeping text intact 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter = ',', dtype='object')
names = ('sepallength','sepalwidth','petallength','petalwidth','species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [25]:
#20 extract a particular column from 1d array of tuples
iris_1d = np.genfromtxt(url,delimiter=',',dtype=None)
print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


<ipython-input-25-e6de27ce658b>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url,delimiter=',',dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [26]:
#21 convert a 1d array of tuples to a 2d numpy array
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [27]:
#21 alternative import only the first 4 columns from source url
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [28]:
#22 compute mean,median,standard deviation of a numpy array
sepallength = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])
mean,median,sd = np.mean(sepallength),np.median(sepallength),np.std(sepallength)
print(mean,median,sd)

5.843333333333334 5.8 0.8253012917851409


In [29]:
#23 normalize an array so the values range exactly between 0 and 1
smax, smin = sepallength.max(),sepallength.min()
n = (sepallength - smin)/(smax - smin)
print(n)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [32]:
#24 compute softmax score 
iris = np.genfromtxt(url,delimiter=',',dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

def softmax(x):
    """compute softmax score for each sets of scores in x"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812