In [1]:
#25 find the percentile scores of a numpy array for example find the 5th and 95th percentile of iris's sepallength
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
a1 = np.percentile(sepallength, q=[5,95])
print(a1)

[4.6   7.255]


In [3]:
#26 insert values at random positions in an array> insert values at 20 random positions in iris_2d dataset
iris_2d = np.genfromtxt(url,delimiter=',', dtype='object')
# method 1 
i, j = np.where(iris_2d) # i and j contains the row and column numbers of 600 elements of iris
np.random.seed(100)
iris_2d[np.random.choice((i),20), np.random.choice((j),20)] = np.nan
print(iris_2d[:10])
# method 2 
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]
[[b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [13]:
#27 find the position of missing values in numpy array
iris_2d = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20), np.random.randint(4, size=20)] = np.nan
print("Number of missing values: \n", np.isnan(iris_2d[:,0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:,0])))

Number of missing values: 
 5
Position of missing values: 
 (array([  2,  53,  99, 100, 111], dtype=int64),)


In [11]:
#28 filter a numpy array based on two or more conditions 
# find the rows of iris_2d that has petallength(3rd column)>1.5 and sepallength(1st column)<5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2]>1.5) & (iris_2d[:, 0]<5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [14]:
#29 drop rows containing a missing value from a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20), np.random.randint(4, size=20)] = np.nan
# method 1
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

# method 2
iris_2d[np.sum(np.isnan(iris_2d), axis=1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
#30 find conrrelation between two columns of a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
# method 1
np.corrcoef(iris[:,0],iris[:,2])[0,1]
# method 2 
from scipy.stats.stats import pearsonr
corr, p_value = pearsonr(iris[:,0],iris[:,2])
print(corr)

0.8717541573048713


In [23]:
#31 find if a given array has any null values
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [26]:
#32 replace all missing values with 0 in a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:6]

array([[5.1, 3.5, 0. , 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [27]:
#33 find the count of unique values in a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
name = ('sepallength', 'sepalwidth', 'petallength','patalwidth','species')
# extract species column as an array
species = np.array([row.tolist()[4] for row in iris])
# get unique values and counts
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [28]:
#34 convert a numeric to a categorical text array: Bin petallength column to form a text array so less than 3 > small
# 3-5 > medium greater than 5 > large
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
name = ('sepallength', 'sepalwidth', 'petallength','patalwidth','species')

# Bin petallength
petal_length_bin = np.digitize(iris[:,2].astype('float'),[0,3,5,10])
# Map it to respective category
label_map = {1:'small', 2:'medium', 3:'large', 4:np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# view
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [31]:
#35 create a new column from existing column of a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url,delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength','patalwidth','species')

# compute volume
sepallength = iris_2d[:,0].astype('float')
petallength = iris_2d[:,2].astype('float')
volume = (np.pi * petallength * (sepallength**2)) / 3

# add new column to dataset
volume = volume[:, np.newaxis]
out = np.hstack([iris_2d, volume])
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)