In [6]:
import numpy as np
#36 probabilistic sampling in numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
# get column of species
species = iris[:4]
# method 1 generate probablistically
np.random.seed(100)
a1 = np.array(['Iris-setosa','Iris-versicolor','Iris-virginica'])
species_out = np.random.choice(a1, 150, p=[0.5,0.25,0.25])
print(np.unique(species_out,return_counts=True))
# method 2 probablistic smapling 
np.random.seed(100)
probs = np.r_[np.linspace(0, .500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
#pecies_out = species[index]
#rint(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36], dtype=int64))


In [8]:
#37 get the second largest value of an array when grouped by another array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
# get the species and petal length columns
petal_len_setosa = iris[iris[:,4] == b'Iris-setosa',[2]].astype('float')
# get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [9]:
#38 sort a 2d array by a column of 0 pepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
name = ('sepallength', 'sepalwidth', 'petallength','patalwidth','species')
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [10]:
#39 find most frequent value in a numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
vals, counts = np.unique(iris[:,2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [13]:
#40 find the position of the first occurence of a value greater than a given value
# find the position of the first occurence of a value greater than 1 in petalwidth 4th column
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
np.argwhere(iris[:,3].astype(float)>1.0)[0]

array([50], dtype=int64)

In [16]:
#41 replace all values greater than a given value to a given cutoff
# greater than 30 to 30 and less than 10 to 10
# method 1 using np.clip
np.set_printoptions(precision=2)
np.random.seed(100)
a2 = np.random.uniform(1,50,20)
np.clip(a2, a_min=10, a_max=30)

# method 2 useing np.where
print(np.where(a2<10,10, np.where(a2>30,30,a2)))


[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [21]:
#42 get the positions of top n values from a numpy array for example postions for top 5 values 
np.random.seed(100)
a3 = np.random.uniform(1,50,20)
# method 1
print(a3.argsort()[:5])
# method 2
np.argpartition(-a3,5)[:5]
# below methods get you the values
np.sort(a3)[-5:]
a3[a3.argsort()][-5:]
np.partition(a3,kth=-5)[-5:]


[ 4 13  5  8 17]


array([41.  , 41.47, 42.39, 44.67, 48.95])