In [4]:
import numpy as np
#43 convert an array of arrays into a flat 1d array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
a1 = np.arange(3)
print(a1)
a2 = np.arange(3,7)
print(a2)
a3 = np.arange(7,10)
print(a3)
a4 = np.array([a1,a2,a3])
print(a4)
a5 = np.array([ a for arr in a4 for a in arr])
print(a5)
a6 = np.concatenate(a4)
print(a6)

[0 1 2]
[3 4 5 6]
[7 8 9]
[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


<ipython-input-4-9b0606ad0cbe>:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a4 = np.array([a1,a2,a3])


In [5]:
#44 generate one-hot encodings for an array in numpy
np.random.seed(101)
a7 = np.random.randint(1,4,size=6)
print(a7)

[2 3 2 2 2 1]


In [6]:
def one_hot_encodings(a7):
    uniqs = np.unique(a7)
    out = np.zeros((a7.shape[0], uniqs.shape[0]))   # meaning?
    for i, k in enumerate(a7):
        out[i, k-1] = 1                             # meaning?
    return out

one_hot_encodings(a7)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
#45 create row numbers grouped by a categorical variable> meaning?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url,delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [9]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]


In [11]:
#46 create group id based on a given categorical variable
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url,delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
# method 1
output1 = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
print(output1)
# method 2
output2 = []
uniqs = np.unique(species_small)

for val in uniqs: # uniq values in group
    for s in species_small[species_small==val]: # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0] # groupid
        output2.append(groupid)

print(output2)

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]


In [15]:
#47 create rank items in an array
np.random.seed(10)
a8 = np.random.randint(20, size=10)
print(a8)
print(a8.argsort())

[ 9  4 15  0 17 16 17  8  9  0]
[3 9 1 7 0 8 2 5 4 6]


In [17]:
#48 rank items in a multidimentional array 
np.random.seed(10)
a9 = np.random.randint(20,size=[2,5])
print(a9)
print(a9.ravel().argsort().argsort().reshape(a9.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [25]:
#49 find the maximum value in each row of a 2d array
np.random.seed(100)
a10 = np.random.randint(1,10,[5,3])
print(a10)
print(np.amax(a10, axis=1))
print(np.apply_along_axis(np.max, arr=a10, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[9 8 6 3 9]


In [28]:
#50 compute the min_by_max for each row for a numpy 2d array
np.random.seed(100)
a11 = np.random.randint(1,10,[5,3])
print(a11)
output = np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a10, axis=1)
print(output)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0.44444444 0.125      0.5        1.         0.11111111]


In [31]:
#51 find the duplicate records in a numpy array
np.random.seed(100)
a12 = np.random.randint(0,5,10)
print('Array:', a12)
out = np.full(a12.shape[0], True)
unique_positions = np.unique(a12, return_index=True)[1]
out[unique_positions] = False # why false
print(out)

Array: [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [36]:
#52 find the mean of a numeric column grouped by a categorical column in a 2d numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',', dtype='object')
name = ('sepallength', 'sepalwidth', 'petallength','patalwidth','species')
# method 1
numeric_column = iris[:,1].astype('float')   # sepalwidth
grouping_column = iris[:,4]                  # species
output2 = [[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]
print(output2)
# method 2
output3 = []
for group_val in np.unique(grouping_column):
    output3.append([group_val, numeric_column[grouping_column==group_val].mean()])
print(output3)

[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]
[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]
