In [3]:
#53 convert a PIL image to numpy array and convert it back 
import numpy as np 
from io import BytesIO
from PIL import Image
import PIL, requests
url = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(url)
# read it as Image
I = Image.open(BytesIO(response.content))
# resize
I = I.resize([150,150])
# convert to numpy array
arr = np.asarray(I)
print(arr)
# convert array back to Image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

[[[  9  72 125]
  [ 10  73 126]
  [ 11  74 127]
  ...
  [ 44 104 154]
  [ 43 104 152]
  [ 42 103 147]]

 [[ 10  73 126]
  [ 11  74 127]
  [ 11  74 127]
  ...
  [ 45 105 155]
  [ 45 106 154]
  [ 46 107 152]]

 [[ 11  73 127]
  [ 12  74 128]
  [ 12  75 128]
  ...
  [ 47 107 157]
  [ 46 107 156]
  [ 46 106 155]]

 ...

 [[ 35  50  59]
  [ 31  52  66]
  [ 19  36  47]
  ...
  [ 20  52  67]
  [ 26  57  78]
  [ 26  59  83]]

 [[ 31  52  64]
  [ 33  62  78]
  [ 37  56  72]
  ...
  [ 21  49  62]
  [ 24  50  68]
  [ 21  48  66]]

 [[ 23  51  65]
  [ 26  60  79]
  [ 28  58  75]
  ...
  [ 17  64  92]
  [ 25  67  97]
  [ 21  56  83]]]


In [6]:
#54 drop all missing values from a numpy array
a1 = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a1[~np.isnan(a1)])

[1. 2. 3. 5. 6. 7.]


In [8]:
#55 compute euclidean distance between two arrays
a2 = np.array([1,2,3,4,5])
a3 = np.array([4,5,6,7,8])
dist = np.linalg.norm(a2-a3)
print(dist)

6.708203932499369


In [9]:
#56 find all the local maxima or peaks in a 1d array
a4 = np.array([1,3,7,1,2,6,0,1])
doublediff = np.diff(np.sign(np.diff(a4)))
peak_locations = np.where(doublediff== -2)[0] + 1 # 2 and 5 are the positions of peak values 7 and 6 but why == -2?
print(peak_locations)

[2 5]


In [12]:
#57 subtract a 1d array from a 2d array, where each item of 1d array substracts from respective row
a_1d = np.array([1,2,3])
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a_2d - a_1d[:,None])
print('number of dim:',a_2d.ndim)
print('shape:', a_2d.shape)
print('size:', a_2d.size)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
number of dim: 2
shape: (3, 3)
size: 9


In [14]:
#58 find the index of n'th repetition of an item in an array> find the index of 5th repetition of number 1 in x
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
n = 5
# method 1 list comprehension
[i for i, v in enumerate(x) if v==1][n-1]
# method 2 Numpy version
np.where(x==1)[0][n-1]

8

In [15]:
#59 convert numpy's datetime64 object to datetime's datetime object
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [16]:
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [18]:
#60 compute the moving average of a numpy array> compute a moving average of window size 3 for a given 1d array
np.random.seed(100)
Z = np.random.randint(10,size=10)
print('array:', Z)

# method 1
def moving_average(a,n=3):
    ret = np.cumsum(a, dtype=float) # meaning?
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]/n

moving_average(Z,n=3).round(2)



array: [8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [21]:
#61 create a numpy array sequence given only the starting point, length and the step
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [25]:
#62 fill in missing dates in an irregular series of numpy dates: non-continuous dates to continuous sequence of dates 
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'),2)
print(dates)
# method 1
filled_in = np.array([np.arange(date, (date + d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
output = np.hstack([filled_in, dates[-1]])
print(output)
# method 2 for loop version
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)
output1 = np.hstack([filled_in, dates[-1]])
print(output1)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']
