In [4]:
#01 Import numpy and check the version number
import numpy as np
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LylionCj/anaconda3\\Library\\include']


In [9]:
#02 Create a 1D array of numbers from 0 to 20
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
#03 create a 4 X 6 numpy array of all True's
arrT = np.full((4,6), True, dtype=bool)
arrT

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [14]:
#03 alternate method
arrt = np.ones((4,6),dtype=bool)
arrt

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [30]:
#04 np.ones
arr1 = np.ones(5)
print(arr1)
arr2 = np.ones((5,), dtype=int)
print(arr2)
arr3 = np.ones((5,), dtype=bool)
print(arr3)
arr4 = np.ones((2,1))
print(arr4)
s = (2,2)
arr5 = np.ones(s)
print(arr5)
arr6 = np.ones((3,5))
print(arr6)
x = np.arange(6)
x = x.reshape((2,3))
print(x)
arr7 = np.ones_like(x)
print(arr7)
arr8 = np.zeros_like(x)
print(arr8)
arr9 = np.empty([2,2])
print(arr9)
arr10 = np.empty([2,2],dtype=int)
print(arr10)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[ True  True  True  True  True]
[[1.]
 [1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[1. 1.]
 [1. 1.]]
[[         0 1072693248]
 [         0 1072693248]]


In [38]:
#04 extract items that satify a given condition from 1D array
arr11 = np.array([0,1,2,3,4,5,6,7,8,9])
arr12 = arr11[arr11 % 2 == 0]
print(arr12)
arr11[arr11 % 2 == 1]= -1
print(arr11)
arr11[arr11 % 2 == 0]= 3
print(arr11)

[0 2 4 6 8]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 3 -1  3 -1  3 -1  3 -1  3 -1]


In [39]:
#05 reshape an arrat
arr13 = np.arange(10)
arr13.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
#06 stack two arrays 
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a)
print(b)
c = np.concatenate((a,b),axis=1)
print(c)
d = np.hstack((a,b))
print(d)
e = np.vstack((a,b))
print(e)
f = np.c_[a,b]
print(f)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [49]:
#07 generate custom sequences in numpy without hardcoding
j = np.array([1,2,3])
k = np.r_[np.repeat(j,3), np.tile(j,3)]
print(k)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [50]:
#08 get common items between two numpy arrays
a1 = np.array([1,2,3,2,3,4,3,4,5,6])
a2 = np.array([7,2,10,2,7,4,9,4,9,8])
a3 = np.intersect1d(a1,a2)
print(a3)

[2 4]


In [60]:
#09 remove items from one array that exist in another array
a4 = np.setdiff1d(a1,a2)
print(a4)

[1 3 5 6]


In [63]:
#10 get the positions where elements of two arrays match
a5 = np.where(a1 == a2)
print(a5)

(array([1, 3, 5, 7], dtype=int64),)


In [64]:
#11 extract all numbers between a given range from array
a6 = np.array([2,6,1,9,10,3,27])
a6[(a6 >= 5) & (a6 <= 10)]

array([ 6,  9, 10])

In [65]:
#12 Function Vectorization construct a function to select the bigger number from two corresponding elements of two arrays to form a new array

def max(x,y):
    """get the maxium of two items"""
    if x >= y:     # where here x can repersent its elements?
        return x
    else:
        return y

pair_max = np.vectorize(max, otypes=[float])

a7 = np.array([5,7,9,8,6,4,5])
a8 = np.array([6,3,4,8,9,7,1])

pair_max(a7,a8)

array([6., 7., 9., 8., 9., 7., 5.])

In [66]:
def act(x,y):
    """if x>y return x-y or x+y """
    if x >= y:
        return x-y
    else:
        return x+y

pair_act = np.vectorize(act)

a7 = np.array([5,7,9,8,6,4,5])
a8 = np.array([6,3,4,8,9,7,1])

pair_act(a7,a8)

array([11,  4,  5,  0, 15, 11,  4])